<?php
# URL OF LATEST COUNTRY FILE - Paste URL of BIG_CTY.ZIP file
$url='https://www.country-files.com/bigcty/download/2022/bigcty-20220804.zip';

# LEGAL ADDITION after / sign on callsign
# not to be changed
$legal=array("P","A","M","MM","AM");

# ILLEGAL ADDITION after / sign on callsign
# can be extended in same format
$illegal=array("QRP","YOTA","LH","LHT","LS","J","JOTA","PM","MILL","FF",);

# NUMBER MODIFIERS
# used in Italy, Russia, USA, Canada, ...
?>